Attribute VB_Name = "netsend"
'******************************************************************************************
'***** VB Compress Pro 6.10.32 generated this copy of netsend.bas on Thu 1/25/01 @ 4:29 PM 
'***** Mode: AutoSelect Standard Mode (Internal References Only)***************************
'******************************************************************************************
'* Note: VBC id'd the following unreferenced items and handled them as described:         *
'*                                                                                        *
'* Private Constants (Removed)                                                            *
'*  NERR_Success                                                                          *
'*                                                                                        *
'* Private Declares (Removed)                                                             *
'*  NetMessageBufferSend                                                                  *
'*                                                                                        *
'* Public Procedures (Removed)                                                            *
'*  BroadcastMessage                                                                      *
'******************************************************************************************

'I was going to just use Shell() with net.com, but
'on some of the machines I tried this on it wouldn't
'work???
'Anyway you can send your praise of this code to
'http://www.vb-world.com/internet/tip514.html




